import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {Attempt,Player,Room,isSupabaseReady,messageFor,supabase} from './supabase'
import {Point,ScoreResult,ratingFor,scoreStroke} from './scoring'

type Screen='home'|'form'|'lobby'|'draw'|'result'|'session'
type Session={roomId:string;roomCode:string;playerId:string;name:string;isHost:boolean}
const SESSION_KEY='circle-session-v1',BEST_KEY='circle-solo-best-v1'
const code=()=>Array.from({length:5},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('')
const simplify=(pts:Point[])=>pts.filter((_,i)=>i%Math.max(1,Math.ceil(pts.length/90))===0).map(p=>({x:+p.x.toFixed(1),y:+p.y.toFixed(1)}))

function Mark({small=false}:{small?:boolean}){return <div className={'mark '+(small?'small':'')} aria-hidden="true"><i/></div>}

function DrawPad({onDone,disabled=false,preview}:{onDone?:(points:Point[],r:ScoreResult)=>void;disabled?:boolean;preview?:{points:Point[];result?:ScoreResult;score?:ScoreResult}}){
  const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),pts=useRef<Point[]>([])
  const render=useCallback((points:Point[],fit?:ScoreResult)=>{const c=canvas.current;if(!c)return;const d=devicePixelRatio||1,rect=c.getBoundingClientRect();if(c.width!==rect.width*d||c.height!==rect.height*d){c.width=rect.width*d;c.height=rect.height*d}const x=c.getContext('2d')!;x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,rect.width,rect.height);x.lineJoin='round';x.lineCap='round';x.lineWidth=7;x.strokeStyle='#171717';if(points.length){x.beginPath();x.moveTo(points[0].x,points[0].y);points.slice(1).forEach(p=>x.lineTo(p.x,p.y));x.stroke()}if(fit?.valid){x.beginPath();x.arc(fit.center.x,fit.center.y,fit.radius,0,Math.PI*2);x.setLineDash([7,7]);x.lineWidth=2;x.strokeStyle='#ff694f';x.stroke();x.setLineDash([])}},[])
  useEffect(()=>{if(preview)render(preview.points,preview.result??preview.score)},[preview,render])
  useEffect(()=>{const f=()=>preview&&render(preview.points,preview.result??preview.score);addEventListener('resize',f);return()=>removeEventListener('resize',f)},[preview,render])
  const pos=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,t:performance.now()}}
  return <canvas ref={canvas} className="draw-pad" aria-label="Circle drawing area" onPointerDown={e=>{if(disabled||preview)return;drawing.current=true;pts.current=[pos(e)];e.currentTarget.setPointerCapture(e.pointerId);render(pts.current)}} onPointerMove={e=>{if(!drawing.current)return;const p=pos(e),last=pts.current.at(-1)!;if(Math.hypot(p.x-last.x,p.y-last.y)>1.5){pts.current.push(p);render(pts.current)}}} onPointerUp={()=>{if(!drawing.current)return;drawing.current=false;const p=pts.current,r=scoreStroke(p);render(p,r);onDone?.(p,r)}} onPointerCancel={()=>{drawing.current=false}}/>
}

function App(){
  const [screen,setScreen]=useState<Screen>('home'),[mode,setMode]=useState<'solo'|'create'|'join'>('solo'),[name,setName]=useState(''),[roomInput,setRoomInput]=useState('')
  const [room,setRoom]=useState<Room|null>(null),[session,setSession]=useState<Session|null>(null),[players,setPlayers]=useState<Player[]>([]),[attempts,setAttempts]=useState<Attempt[]>([])
  const [result,setResult]=useState<{points:Point[];score:ScoreResult}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false)
  const solo=mode==='solo',myAttempt=attempts.find(a=>a.player_id===session?.playerId&&a.round_number===room?.current_round)
  const standings=useMemo(()=>players.map(p=>{const all=attempts.filter(a=>a.player_id===p.id),round=all.find(a=>a.round_number===room?.current_round);return{...p,round,wins:0,avg:all.length?all.reduce((s,a)=>s+a.score,0)/all.length:0,best:all.length?Math.max(...all.map(a=>a.score)):0,played:all.length}}).sort((a,b)=>(b.round?.score||0)-(a.round?.score||0)),[players,attempts,room])
  standings.forEach(p=>p.wins=attempts.filter(a=>a.player_id===p.id&&a.score===Math.max(...attempts.filter(x=>x.round_number===a.round_number).map(x=>x.score))).length)

  const refresh=useCallback(async(s:Session)=>{if(!supabase)return;const [{data:rr},{data:pp},{data:aa}]=await Promise.all([supabase.from('rooms').select('*').eq('id',s.roomId).single(),supabase.from('players').select('*').eq('room_id',s.roomId).order('joined_at'),supabase.from('attempts').select('*').eq('room_id',s.roomId)]);if(rr)setRoom(rr);if(pp)setPlayers(pp);if(aa)setAttempts(aa);const roundAttempts=aa?.filter(a=>a.round_number===rr?.current_round)||[];if(s.isHost&&rr?.status==='drawing'&&pp?.length&&roundAttempts.length>=pp.length){await supabase.from('rooms').update({status:'results'}).eq('id',s.roomId);setRoom({...rr,status:'results'});setScreen('result')}else if(rr?.status==='drawing'&&!roundAttempts.some(a=>a.player_id===s.playerId))setScreen('draw');else if(rr?.status==='results')setScreen('result')},[])
  useEffect(()=>{const saved=localStorage.getItem(SESSION_KEY);if(!saved||!supabase)return;const s=JSON.parse(saved) as Session;setSession(s);setScreen('lobby');refresh(s).catch(()=>localStorage.removeItem(SESSION_KEY))},[refresh])
  useEffect(()=>{if(!supabase||!session)return;const db=supabase;const ch=db.channel(`room:${session.roomId}`).on('postgres_changes',{event:'*',schema:'public',table:'players',filter:`room_id=eq.${session.roomId}`},()=>refresh(session)).on('postgres_changes',{event:'*',schema:'public',table:'attempts',filter:`room_id=eq.${session.roomId}`},()=>refresh(session)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms',filter:`id=eq.${session.roomId}`},()=>refresh(session)).subscribe();return()=>{db.removeChannel(ch)}},[session,refresh])

  async function enter(){setError('');if(!name.trim())return setError('Add a display name first.');if(!isSupabaseReady)return setError('Multiplayer needs Supabase setup. Solo Practice is ready now.');setBusy(true);try{if(mode==='create'){let created:Room|null=null;for(let i=0;i<5&&!created;i++){const {data}=await supabase!.from('rooms').insert({room_code:code(),status:'lobby',reveal_mode:'all_submitted'}).select().single();created=data}if(!created)throw Error('create');const {data:p,error:e}=await supabase!.from('players').insert({room_id:created.id,display_name:name.trim(),is_host:true}).select().single();if(e)throw e;await supabase!.from('rooms').update({host_player_id:p.id}).eq('id',created.id);const s={roomId:created.id,roomCode:created.room_code,playerId:p.id,name:name.trim(),isHost:true};localStorage.setItem(SESSION_KEY,JSON.stringify(s));setSession(s);setRoom({...created,host_player_id:p.id});setPlayers([p]);setScreen('lobby')}else{const {data:r,error:e}=await supabase!.from('rooms').select('*').eq('room_code',roomInput.trim().toUpperCase()).neq('status','closed').single();if(e||!r)throw Error('invalid');const {data:p,error:pe}=await supabase!.from('players').insert({room_id:r.id,display_name:name.trim(),is_host:false}).select().single();if(pe)throw pe;const s={roomId:r.id,roomCode:r.room_code,playerId:p.id,name:name.trim(),isHost:false};localStorage.setItem(SESSION_KEY,JSON.stringify(s));setSession(s);setRoom(r);setScreen('lobby');await refresh(s)}}catch(e){setError(/invalid/.test(String(e))?'That room could not be found or is no longer active.':messageFor(e))}finally{setBusy(false)}}
  async function startRound(){if(!room||!session)return;await supabase!.from('rooms').update({status:'drawing',current_round:room.current_round+1}).eq('id',room.id).eq('host_player_id',session.playerId);setResult(null)}
  async function submit(points:Point[],score:ScoreResult){setResult({points,score});if(!score.valid)return;setScreen('result');if(solo){const best=Math.max(score.score,Number(localStorage.getItem(BEST_KEY)||0));localStorage.setItem(BEST_KEY,String(best));return}if(!room||!session)return;await supabase!.from('attempts').insert({room_id:room.id,player_id:session.playerId,round_number:room.current_round,score:score.score,rating:ratingFor(score.score),points:simplify(points),radial_error:score.radialError,closure_error:score.closureRatio,smoothness_score:score.smoothness,angular_coverage:score.angularCoverage});await refresh(session);const {count}=await supabase!.from('attempts').select('*',{count:'exact',head:true}).eq('room_id',room.id).eq('round_number',room.current_round);if(session.isHost&&count&&count>=players.length)await supabase!.from('rooms').update({status:'results'}).eq('id',room.id)}
  const share=async()=>{if(!session)return;const text=`Join my Circle game! Room: ${session.roomCode}`;if(navigator.share)await navigator.share({title:'Circle',text,url:location.href});else{await navigator.clipboard.writeText(session.roomCode);setCopied(true);setTimeout(()=>setCopied(false),1500)}}
  const home=()=>{setScreen('home');setResult(null);setError('')}

  if(screen==='home')return <main className="home"><header><Mark/><span className="eyebrow">A very serious game</span><h1>CIRCLE<span>.</span></h1><p>Draw one. Find out how round you really are.</p></header><div className="home-actions"><button className="primary" onClick={()=>{setMode('create');setScreen('form')}}>Create game <b>↗</b></button><button onClick={()=>{setMode('join');setScreen('form')}}>Join game <b>→</b></button><button className="ghost" onClick={()=>{setMode('solo');setScreen('draw')}}>Solo practice <b>◎</b></button></div><footer>No sign-up. No geometry degree.</footer></main>
  if(screen==='form')return <main className="panel"><button className="back" onClick={home}>← Back</button><Mark small/><span className="eyebrow">{mode==='create'?'Call the meeting':'Enter the arena'}</span><h2>{mode==='create'?'Create a game':'Join a game'}</h2><label>Your name<input autoFocus maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Maya"/></label>{mode==='join'&&<label>Room code<input className="code-input" maxLength={5} value={roomInput} onChange={e=>setRoomInput(e.target.value.toUpperCase())} placeholder="ABCDE"/></label>}<p className="error" role="alert">{error}</p><button className="primary" disabled={busy} onClick={enter}>{busy?'One moment…':mode==='create'?'Create room':'Join room'} <b>→</b></button></main>
  if(screen==='lobby'&&room&&session)return <main className="panel lobby"><div className="top"><button className="back" onClick={home}>← Home</button><button className="text-btn" onClick={()=>setScreen('session')}>Session stats</button></div><span className="eyebrow">Room code</span><h2 className="room-code">{room.room_code}</h2><button className="share" onClick={share}>{copied?'Copied!':'Share game'} <b>↗</b></button>{session.isHost&&<div className="reveal"><span>Reveal scores</span><button aria-pressed={room.reveal_mode==='all_submitted'} onClick={async()=>{const v=room.reveal_mode==='all_submitted'?'immediate':'all_submitted';setRoom({...room,reveal_mode:v});await supabase!.from('rooms').update({reveal_mode:v}).eq('id',room.id)}}><i/>{room.reveal_mode==='all_submitted'?'When everyone finishes':'As players finish'}</button></div>}<section><div className="section-title"><h3>Players</h3><span>{players.length} joined</span></div><ul className="players">{players.map((p,i)=><li key={p.id}><span className="avatar">{p.display_name[0].toUpperCase()}</span><strong>{p.display_name}{p.id===session.playerId?' (you)':''}</strong>{p.is_host&&<em>Host</em>}<span className="ready">Ready</span></li>)}</ul></section>{session.isHost?<button className="primary dock" onClick={startRound}>Start round {room.current_round+1} <b>→</b></button>:<p className="waiting">Waiting for the host to start…</p>}</main>
  if(screen==='draw')return <main className="game"><div className="game-head"><button className="back" onClick={solo?home:()=>setScreen('lobby')}>×</button><span>{solo?'Solo practice':`Round ${room?.current_round}`}</span><span className="dot">● LIVE</span></div><h2>Draw one circle.</h2><p>One stroke. No do-overs.</p><DrawPad onDone={submit}/>{result&&!result.score.valid&&<div className="toast" role="alert">{result.score.reason}<button onClick={()=>setResult(null)}>Try again</button></div>}<div className="tip"><b>TIP</b> Slow and steady beats fast and wobbly.</div></main>
  if(screen==='result'&&result){const s=result.score;return <main className="result"><div className="game-head"><button className="back" onClick={home}>×</button><span>{solo?'Solo result':`Round ${room?.current_round}`}</span><span/></div><span className="eyebrow">Your circle</span><DrawPad disabled preview={result}/><div className="score"><span>ROUNDNESS</span><strong>{s.score.toFixed(1)}</strong><small>/ 100</small><h2>{ratingFor(s.score)}</h2></div>{import.meta.env.DEV&&<details><summary>Scoring diagnostics</summary><pre>{JSON.stringify({center:s.center,radius:s.radius,radialStdDev:s.radialStdDev,radialError:s.radialError,closureRatio:s.closureRatio,closureScore:s.closureScore,smoothness:s.smoothness,angularCoverage:s.angularCoverage,coverageScore:s.coverageScore,retracePenalty:s.retracePenalty,final:s.score},null,2)}</pre></details>}{solo?<div className="result-actions"><button className="primary" onClick={()=>{setResult(null);setScreen('draw')}}>Try again <b>↻</b></button><p>Personal best: <strong>{Math.max(s.score,Number(localStorage.getItem(BEST_KEY)||0)).toFixed(1)}</strong></p></div>:<><Leaderboard standings={standings} hidden={room?.reveal_mode==='all_submitted'&&attempts.filter(a=>a.round_number===room.current_round).length<players.length}/>{session?.isHost&&room?.status==='results'&&<button className="primary" onClick={startRound}>Next round <b>→</b></button>} {!myAttempt&&<p>Waiting for your attempt…</p>}</>}</main>}
  if(screen==='session')return <main className="panel"><button className="back" onClick={()=>setScreen('lobby')}>← Lobby</button><span className="eyebrow">This room</span><h2>Session stats</h2><div className="stats-head"><b>{room?.current_round||0}</b><span>Rounds played</span></div><ul className="stats">{standings.sort((a,b)=>b.wins-a.wins||b.avg-a.avg).map((p,i)=><li key={p.id}><b>{i+1}</b><span><strong>{p.display_name}</strong><small>{p.played} played · {p.wins} wins</small></span><em>{p.avg.toFixed(1)} avg<br/>{p.best.toFixed(1)} best</em></li>)}</ul></main>
  return null
}

function Leaderboard({standings,hidden}:{standings:any[];hidden:boolean}){return <section className="leader"><div className="section-title"><h3>Leaderboard</h3><span>{hidden?'Scores hidden':'Round results'}</span></div>{hidden?<p className="waiting">Waiting for everyone to finish…</p>:<ol>{standings.filter(p=>p.round).map((p,i)=><li className={i===0?'winner':''} key={p.id}><b>{i+1}</b><span><strong>{p.display_name}</strong><small>{ratingFor(p.round.score)}</small></span><em>{p.round.score.toFixed(1)}</em></li>)}</ol>}</section>}
export default App
